name: Test Actions

on:
  pull_request:
    branches:
      - v1
  push:
    branches:
      - v1
  workflow_dispatch:

concurrency:
  group:
    ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  test-action:
    strategy:
      matrix:
        targets:
          - '!(*musl*|*windows-arm64*|*android*|*freebsd*)' # xgo
          - 'linux-*-musl*' #musl
          - 'windows-arm64' #win-arm64
          - 'android-*' #android
          - 'freebsd-*' #freebsd
    name: GitHub Actions Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Test Local Action
        id: test-action
        uses: ./
        with:
          dir: './example'
          targets: ${{ matrix.targets }}
          musl-target-format: $os-$musl-$arch

      - name: Print Output
        id: output
        run: echo "${{ steps.test-action.outputs.files }}"
