name: Test Actions

on:
  pull_request:
    branches:
      - v1
  push:
    branches:
      - dev
  workflow_dispatch:

concurrency:
  group:
    ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  test-action:
    strategy:
      matrix:
        targets:
          - '!(*musl*|*windows-arm64*|*android*|*freebsd*)' # xgo
          - 'linux-*-musl*' #musl
          - 'windows-arm64' #win-arm64
          - 'android-*' #android
          - 'freebsd-*' #freebsd
    name: GitHub Actions Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Test Local Action
        id: test-action
        uses: ./
        with:
          dir: './example'
          targets: ${{ matrix.targets }}
          musl-target-format: $os-$musl-$arch
          x-flags: |
            example/main.owner=$owner
            example/main.repo=$repo
            example/main.target=$target
            example/main.sha=$sha
            example/main.short_sha=$short_sha
            example/main.pr=$pr
            example/main.ext=$ext
            example/main.tag=$tag
            example/main.hostname=$hostname
            example/main.username=$username
            example/main.built_on=$built_on
            example/main.built_at=$built_at
            example/main.git_author=$git_author
            example/main.git_commit=$git_commit
            example/main.go_version=$go_version

      - name: Print Output
        id: output
        run: echo "${{ steps.test-action.outputs.files }}"
